### ISSUE TITLE
Migrate the code instead

### ISSUE THREAD

**Issue by TomasVotruba** [laminas/laminas-zendframework-bridge#18]
I see the implementation basically replaces "Zend" with "Laminas" in namespace. This step introduces possible conflict of 2 classes, one with Laminas, one with Zend. It also adds extra work with eventual migration.

Why not migrate the namespace when laminas packages are used already?

I work on a tool that instantly migrates PHP code - [Rector](https://github.com/rectorphp/rector). It can do this migration as well:

```yaml
# configure rector.yaml
services:
    Rector\Rector\Namespace_\RenameNamespaceRector:
        Zend: Laminas
```

```bash
# run
vendor/bin/rector process src/SomeOldZendCode
```

## Result

```diff
-use Zend\Something;
+use Laminas\Something;

 class SomeController
 {
     public function run()
     {
-        return new Zend\Response;
+        return new Laminas\Response;
     }
 }
```
